### ISSUE TITLE
Link to v3 wrong

### ISSUE THREAD

**Issue by nerdoc** [pesor/Fronius-Data-Manager-ver-2#1]
The link in your readme to the "newer" version is a 404 - could you update that? I didn't find v3.

**Comment by pesor** [comment]
Actually, I have been working on this project for a Loong time.

I am right now on version 4.0 / beta, which works very well.

I will upload it tomorrow, and inform you when it is ready for download.

**Comment by pesor** [comment]
The Fronius Data Manager version 4.0.0 is now available on the Github on this

URL: https://github.com/pesor/Fronius-Data-Manager

The link in version 2 have been updated also.

Please do not hesitate to contact me with suggestions, and questions.
